// Code generated by Kitex v0.16.0. DO NOT EDIT.

package llmkeyservicev0_1

import (
	"context"
	v0_1 "github.com/S-zhi/blender-shot-preview/kitex_gen/handler/v0_1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ManageLLMKey(ctx context.Context, request *v0_1.ManageLLMKeyRequest, callOptions ...callopt.Option) (r *v0_1.ManageLLMKeyResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kLLMKeyServiceV0_1Client{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kLLMKeyServiceV0_1Client struct {
	*kClient
}

func (p *kLLMKeyServiceV0_1Client) ManageLLMKey(ctx context.Context, request *v0_1.ManageLLMKeyRequest, callOptions ...callopt.Option) (r *v0_1.ManageLLMKeyResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ManageLLMKey(ctx, request)
}
