// Code generated by Kitex v0.16.0. DO NOT EDIT.

package llmkeyservicev0_1

import (
	"context"
	"errors"
	v0_1 "github.com/S-zhi/blender-shot-preview/kitex_gen/handler/v0_1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ManageLLMKey": kitex.NewMethodInfo(
		manageLLMKeyHandler,
		newLLMKeyServiceV0_1ManageLLMKeyArgs,
		newLLMKeyServiceV0_1ManageLLMKeyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	lLMKeyServiceV0_1ServiceInfo                = NewServiceInfo()
	lLMKeyServiceV0_1ServiceInfoForClient       = NewServiceInfoForClient()
	lLMKeyServiceV0_1ServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return lLMKeyServiceV0_1ServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return lLMKeyServiceV0_1ServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return lLMKeyServiceV0_1ServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "LLMKeyServiceV0_1"
	handlerType := (*v0_1.LLMKeyServiceV0_1)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "v0_1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.0",
		Extra:           extra,
	}
	return svcInfo
}

func manageLLMKeyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*v0_1.LLMKeyServiceV0_1ManageLLMKeyArgs)
	realResult := result.(*v0_1.LLMKeyServiceV0_1ManageLLMKeyResult)
	success, err := handler.(v0_1.LLMKeyServiceV0_1).ManageLLMKey(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLLMKeyServiceV0_1ManageLLMKeyArgs() interface{} {
	return v0_1.NewLLMKeyServiceV0_1ManageLLMKeyArgs()
}

func newLLMKeyServiceV0_1ManageLLMKeyResult() interface{} {
	return v0_1.NewLLMKeyServiceV0_1ManageLLMKeyResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ManageLLMKey(ctx context.Context, request *v0_1.ManageLLMKeyRequest) (r *v0_1.ManageLLMKeyResponse, err error) {
	var _args v0_1.LLMKeyServiceV0_1ManageLLMKeyArgs
	_args.Request = request
	var _result v0_1.LLMKeyServiceV0_1ManageLLMKeyResult
	if err = p.c.Call(ctx, "ManageLLMKey", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
