// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package v0_1

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type AssetType int64

const (
	AssetType_MODEL_3D    AssetType = 1
	AssetType_SHOT_PRESET AssetType = 2
	AssetType_MATERIAL    AssetType = 3
	AssetType_ANIMATION   AssetType = 4
)

func (p AssetType) String() string {
	switch p {
	case AssetType_MODEL_3D:
		return "MODEL_3D"
	case AssetType_SHOT_PRESET:
		return "SHOT_PRESET"
	case AssetType_MATERIAL:
		return "MATERIAL"
	case AssetType_ANIMATION:
		return "ANIMATION"
	}
	return "<UNSET>"
}

func AssetTypeFromString(s string) (AssetType, error) {
	switch s {
	case "MODEL_3D":
		return AssetType_MODEL_3D, nil
	case "SHOT_PRESET":
		return AssetType_SHOT_PRESET, nil
	case "MATERIAL":
		return AssetType_MATERIAL, nil
	case "ANIMATION":
		return AssetType_ANIMATION, nil
	}
	return AssetType(0), fmt.Errorf("not a valid AssetType string")
}

func AssetTypePtr(v AssetType) *AssetType { return &v }
func (p *AssetType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = AssetType(result.Int64)
	return
}

func (p *AssetType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type AssetStatus int64

const (
	AssetStatus_AVAILABLE  AssetStatus = 1
	AssetStatus_PROCESSING AssetStatus = 2
	AssetStatus_ARCHIVED   AssetStatus = 3
)

func (p AssetStatus) String() string {
	switch p {
	case AssetStatus_AVAILABLE:
		return "AVAILABLE"
	case AssetStatus_PROCESSING:
		return "PROCESSING"
	case AssetStatus_ARCHIVED:
		return "ARCHIVED"
	}
	return "<UNSET>"
}

func AssetStatusFromString(s string) (AssetStatus, error) {
	switch s {
	case "AVAILABLE":
		return AssetStatus_AVAILABLE, nil
	case "PROCESSING":
		return AssetStatus_PROCESSING, nil
	case "ARCHIVED":
		return AssetStatus_ARCHIVED, nil
	}
	return AssetStatus(0), fmt.Errorf("not a valid AssetStatus string")
}

func AssetStatusPtr(v AssetStatus) *AssetStatus { return &v }
func (p *AssetStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = AssetStatus(result.Int64)
	return
}

func (p *AssetStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type AssetView struct {
	AssetId       string      `thrift:"asset_id,1,required" frugal:"1,required,string" json:"asset_id"`
	Name          string      `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	AssetType     AssetType   `thrift:"asset_type,3,required" frugal:"3,required,AssetType" json:"asset_type"`
	FileFormat    string      `thrift:"file_format,4,required" frugal:"4,required,string" json:"file_format"`
	FileSizeBytes int64       `thrift:"file_size_bytes,5,required" frugal:"5,required,i64" json:"file_size_bytes"`
	StorageUri    string      `thrift:"storage_uri,6,required" frugal:"6,required,string" json:"storage_uri"`
	ThumbnailUri  *string     `thrift:"thumbnail_uri,7,optional" frugal:"7,optional,string" json:"thumbnail_uri,omitempty"`
	Status        AssetStatus `thrift:"status,8,required" frugal:"8,required,AssetStatus" json:"status"`
	Tags          []string    `thrift:"tags,9,optional" frugal:"9,optional,list<string>" json:"tags,omitempty"`
	CreatedAt     string      `thrift:"created_at,10,required" frugal:"10,required,string" json:"created_at"`
	UpdatedAt     string      `thrift:"updated_at,11,required" frugal:"11,required,string" json:"updated_at"`
	Description   *string     `thrift:"description,12,optional" frugal:"12,optional,string" json:"description,omitempty"`
}

func NewAssetView() *AssetView {
	return &AssetView{}
}

func (p *AssetView) InitDefault() {
}

func (p *AssetView) GetAssetId() (v string) {
	return p.AssetId
}

func (p *AssetView) GetName() (v string) {
	return p.Name
}

func (p *AssetView) GetAssetType() (v AssetType) {
	return p.AssetType
}

func (p *AssetView) GetFileFormat() (v string) {
	return p.FileFormat
}

func (p *AssetView) GetFileSizeBytes() (v int64) {
	return p.FileSizeBytes
}

func (p *AssetView) GetStorageUri() (v string) {
	return p.StorageUri
}

var AssetView_ThumbnailUri_DEFAULT string

func (p *AssetView) GetThumbnailUri() (v string) {
	if !p.IsSetThumbnailUri() {
		return AssetView_ThumbnailUri_DEFAULT
	}
	return *p.ThumbnailUri
}

func (p *AssetView) GetStatus() (v AssetStatus) {
	return p.Status
}

var AssetView_Tags_DEFAULT []string

func (p *AssetView) GetTags() (v []string) {
	if !p.IsSetTags() {
		return AssetView_Tags_DEFAULT
	}
	return p.Tags
}

func (p *AssetView) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *AssetView) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

var AssetView_Description_DEFAULT string

func (p *AssetView) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return AssetView_Description_DEFAULT
	}
	return *p.Description
}
func (p *AssetView) SetAssetId(val string) {
	p.AssetId = val
}
func (p *AssetView) SetName(val string) {
	p.Name = val
}
func (p *AssetView) SetAssetType(val AssetType) {
	p.AssetType = val
}
func (p *AssetView) SetFileFormat(val string) {
	p.FileFormat = val
}
func (p *AssetView) SetFileSizeBytes(val int64) {
	p.FileSizeBytes = val
}
func (p *AssetView) SetStorageUri(val string) {
	p.StorageUri = val
}
func (p *AssetView) SetThumbnailUri(val *string) {
	p.ThumbnailUri = val
}
func (p *AssetView) SetStatus(val AssetStatus) {
	p.Status = val
}
func (p *AssetView) SetTags(val []string) {
	p.Tags = val
}
func (p *AssetView) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *AssetView) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}
func (p *AssetView) SetDescription(val *string) {
	p.Description = val
}

func (p *AssetView) IsSetThumbnailUri() bool {
	return p.ThumbnailUri != nil
}

func (p *AssetView) IsSetTags() bool {
	return p.Tags != nil
}

func (p *AssetView) IsSetDescription() bool {
	return p.Description != nil
}

func (p *AssetView) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AssetView(%+v)", *p)
}

var fieldIDToName_AssetView = map[int16]string{
	1:  "asset_id",
	2:  "name",
	3:  "asset_type",
	4:  "file_format",
	5:  "file_size_bytes",
	6:  "storage_uri",
	7:  "thumbnail_uri",
	8:  "status",
	9:  "tags",
	10: "created_at",
	11: "updated_at",
	12: "description",
}

type ListAssetsRequest struct {
	UserId       string     `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
	AssetType    *AssetType `thrift:"asset_type,2,optional" frugal:"2,optional,AssetType" json:"asset_type,omitempty"`
	QueryKeyword *string    `thrift:"query_keyword,3,optional" frugal:"3,optional,string" json:"query_keyword,omitempty"`
	PageSize     *int32     `thrift:"page_size,4,optional" frugal:"4,optional,i32" json:"page_size,omitempty"`
	PageNum      *int32     `thrift:"page_num,5,optional" frugal:"5,optional,i32" json:"page_num,omitempty"`
}

func NewListAssetsRequest() *ListAssetsRequest {
	return &ListAssetsRequest{}
}

func (p *ListAssetsRequest) InitDefault() {
}

func (p *ListAssetsRequest) GetUserId() (v string) {
	return p.UserId
}

var ListAssetsRequest_AssetType_DEFAULT AssetType

func (p *ListAssetsRequest) GetAssetType() (v AssetType) {
	if !p.IsSetAssetType() {
		return ListAssetsRequest_AssetType_DEFAULT
	}
	return *p.AssetType
}

var ListAssetsRequest_QueryKeyword_DEFAULT string

func (p *ListAssetsRequest) GetQueryKeyword() (v string) {
	if !p.IsSetQueryKeyword() {
		return ListAssetsRequest_QueryKeyword_DEFAULT
	}
	return *p.QueryKeyword
}

var ListAssetsRequest_PageSize_DEFAULT int32

func (p *ListAssetsRequest) GetPageSize() (v int32) {
	if !p.IsSetPageSize() {
		return ListAssetsRequest_PageSize_DEFAULT
	}
	return *p.PageSize
}

var ListAssetsRequest_PageNum_DEFAULT int32

func (p *ListAssetsRequest) GetPageNum() (v int32) {
	if !p.IsSetPageNum() {
		return ListAssetsRequest_PageNum_DEFAULT
	}
	return *p.PageNum
}
func (p *ListAssetsRequest) SetUserId(val string) {
	p.UserId = val
}
func (p *ListAssetsRequest) SetAssetType(val *AssetType) {
	p.AssetType = val
}
func (p *ListAssetsRequest) SetQueryKeyword(val *string) {
	p.QueryKeyword = val
}
func (p *ListAssetsRequest) SetPageSize(val *int32) {
	p.PageSize = val
}
func (p *ListAssetsRequest) SetPageNum(val *int32) {
	p.PageNum = val
}

func (p *ListAssetsRequest) IsSetAssetType() bool {
	return p.AssetType != nil
}

func (p *ListAssetsRequest) IsSetQueryKeyword() bool {
	return p.QueryKeyword != nil
}

func (p *ListAssetsRequest) IsSetPageSize() bool {
	return p.PageSize != nil
}

func (p *ListAssetsRequest) IsSetPageNum() bool {
	return p.PageNum != nil
}

func (p *ListAssetsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListAssetsRequest(%+v)", *p)
}

var fieldIDToName_ListAssetsRequest = map[int16]string{
	1: "user_id",
	2: "asset_type",
	3: "query_keyword",
	4: "page_size",
	5: "page_num",
}

type ListAssetsResponse struct {
	Assets     []*AssetView `thrift:"assets,1,required" frugal:"1,required,list<AssetView>" json:"assets"`
	TotalCount int64        `thrift:"total_count,2,required" frugal:"2,required,i64" json:"total_count"`
}

func NewListAssetsResponse() *ListAssetsResponse {
	return &ListAssetsResponse{}
}

func (p *ListAssetsResponse) InitDefault() {
}

func (p *ListAssetsResponse) GetAssets() (v []*AssetView) {
	return p.Assets
}

func (p *ListAssetsResponse) GetTotalCount() (v int64) {
	return p.TotalCount
}
func (p *ListAssetsResponse) SetAssets(val []*AssetView) {
	p.Assets = val
}
func (p *ListAssetsResponse) SetTotalCount(val int64) {
	p.TotalCount = val
}

func (p *ListAssetsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListAssetsResponse(%+v)", *p)
}

var fieldIDToName_ListAssetsResponse = map[int16]string{
	1: "assets",
	2: "total_count",
}

type RegisterAssetRequest struct {
	UserId        string    `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
	Name          string    `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	AssetType     AssetType `thrift:"asset_type,3,required" frugal:"3,required,AssetType" json:"asset_type"`
	FileFormat    string    `thrift:"file_format,4,required" frugal:"4,required,string" json:"file_format"`
	FileSizeBytes int64     `thrift:"file_size_bytes,5,required" frugal:"5,required,i64" json:"file_size_bytes"`
	StorageUri    string    `thrift:"storage_uri,6,required" frugal:"6,required,string" json:"storage_uri"`
	Description   *string   `thrift:"description,7,optional" frugal:"7,optional,string" json:"description,omitempty"`
	Tags          []string  `thrift:"tags,8,optional" frugal:"8,optional,list<string>" json:"tags,omitempty"`
}

func NewRegisterAssetRequest() *RegisterAssetRequest {
	return &RegisterAssetRequest{}
}

func (p *RegisterAssetRequest) InitDefault() {
}

func (p *RegisterAssetRequest) GetUserId() (v string) {
	return p.UserId
}

func (p *RegisterAssetRequest) GetName() (v string) {
	return p.Name
}

func (p *RegisterAssetRequest) GetAssetType() (v AssetType) {
	return p.AssetType
}

func (p *RegisterAssetRequest) GetFileFormat() (v string) {
	return p.FileFormat
}

func (p *RegisterAssetRequest) GetFileSizeBytes() (v int64) {
	return p.FileSizeBytes
}

func (p *RegisterAssetRequest) GetStorageUri() (v string) {
	return p.StorageUri
}

var RegisterAssetRequest_Description_DEFAULT string

func (p *RegisterAssetRequest) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return RegisterAssetRequest_Description_DEFAULT
	}
	return *p.Description
}

var RegisterAssetRequest_Tags_DEFAULT []string

func (p *RegisterAssetRequest) GetTags() (v []string) {
	if !p.IsSetTags() {
		return RegisterAssetRequest_Tags_DEFAULT
	}
	return p.Tags
}
func (p *RegisterAssetRequest) SetUserId(val string) {
	p.UserId = val
}
func (p *RegisterAssetRequest) SetName(val string) {
	p.Name = val
}
func (p *RegisterAssetRequest) SetAssetType(val AssetType) {
	p.AssetType = val
}
func (p *RegisterAssetRequest) SetFileFormat(val string) {
	p.FileFormat = val
}
func (p *RegisterAssetRequest) SetFileSizeBytes(val int64) {
	p.FileSizeBytes = val
}
func (p *RegisterAssetRequest) SetStorageUri(val string) {
	p.StorageUri = val
}
func (p *RegisterAssetRequest) SetDescription(val *string) {
	p.Description = val
}
func (p *RegisterAssetRequest) SetTags(val []string) {
	p.Tags = val
}

func (p *RegisterAssetRequest) IsSetDescription() bool {
	return p.Description != nil
}

func (p *RegisterAssetRequest) IsSetTags() bool {
	return p.Tags != nil
}

func (p *RegisterAssetRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterAssetRequest(%+v)", *p)
}

var fieldIDToName_RegisterAssetRequest = map[int16]string{
	1: "user_id",
	2: "name",
	3: "asset_type",
	4: "file_format",
	5: "file_size_bytes",
	6: "storage_uri",
	7: "description",
	8: "tags",
}

type RegisterAssetResponse struct {
	AssetId string      `thrift:"asset_id,1,required" frugal:"1,required,string" json:"asset_id"`
	Status  AssetStatus `thrift:"status,2,required" frugal:"2,required,AssetStatus" json:"status"`
}

func NewRegisterAssetResponse() *RegisterAssetResponse {
	return &RegisterAssetResponse{}
}

func (p *RegisterAssetResponse) InitDefault() {
}

func (p *RegisterAssetResponse) GetAssetId() (v string) {
	return p.AssetId
}

func (p *RegisterAssetResponse) GetStatus() (v AssetStatus) {
	return p.Status
}
func (p *RegisterAssetResponse) SetAssetId(val string) {
	p.AssetId = val
}
func (p *RegisterAssetResponse) SetStatus(val AssetStatus) {
	p.Status = val
}

func (p *RegisterAssetResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterAssetResponse(%+v)", *p)
}

var fieldIDToName_RegisterAssetResponse = map[int16]string{
	1: "asset_id",
	2: "status",
}

type DeleteAssetRequest struct {
	UserId  string `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
	AssetId string `thrift:"asset_id,2,required" frugal:"2,required,string" json:"asset_id"`
}

func NewDeleteAssetRequest() *DeleteAssetRequest {
	return &DeleteAssetRequest{}
}

func (p *DeleteAssetRequest) InitDefault() {
}

func (p *DeleteAssetRequest) GetUserId() (v string) {
	return p.UserId
}

func (p *DeleteAssetRequest) GetAssetId() (v string) {
	return p.AssetId
}
func (p *DeleteAssetRequest) SetUserId(val string) {
	p.UserId = val
}
func (p *DeleteAssetRequest) SetAssetId(val string) {
	p.AssetId = val
}

func (p *DeleteAssetRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteAssetRequest(%+v)", *p)
}

var fieldIDToName_DeleteAssetRequest = map[int16]string{
	1: "user_id",
	2: "asset_id",
}

type DeleteAssetResponse struct {
	Success bool `thrift:"success,1,required" frugal:"1,required,bool" json:"success"`
}

func NewDeleteAssetResponse() *DeleteAssetResponse {
	return &DeleteAssetResponse{}
}

func (p *DeleteAssetResponse) InitDefault() {
}

func (p *DeleteAssetResponse) GetSuccess() (v bool) {
	return p.Success
}
func (p *DeleteAssetResponse) SetSuccess(val bool) {
	p.Success = val
}

func (p *DeleteAssetResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteAssetResponse(%+v)", *p)
}

var fieldIDToName_DeleteAssetResponse = map[int16]string{
	1: "success",
}

type GetAssetStatsRequest struct {
	UserId string `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
}

func NewGetAssetStatsRequest() *GetAssetStatsRequest {
	return &GetAssetStatsRequest{}
}

func (p *GetAssetStatsRequest) InitDefault() {
}

func (p *GetAssetStatsRequest) GetUserId() (v string) {
	return p.UserId
}
func (p *GetAssetStatsRequest) SetUserId(val string) {
	p.UserId = val
}

func (p *GetAssetStatsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAssetStatsRequest(%+v)", *p)
}

var fieldIDToName_GetAssetStatsRequest = map[int16]string{
	1: "user_id",
}

type GetAssetStatsResponse struct {
	TotalAssets       int64 `thrift:"total_assets,1,required" frugal:"1,required,i64" json:"total_assets"`
	TotalModels       int64 `thrift:"total_models,2,required" frugal:"2,required,i64" json:"total_models"`
	TotalPresets      int64 `thrift:"total_presets,3,required" frugal:"3,required,i64" json:"total_presets"`
	TotalStorageBytes int64 `thrift:"total_storage_bytes,4,required" frugal:"4,required,i64" json:"total_storage_bytes"`
}

func NewGetAssetStatsResponse() *GetAssetStatsResponse {
	return &GetAssetStatsResponse{}
}

func (p *GetAssetStatsResponse) InitDefault() {
}

func (p *GetAssetStatsResponse) GetTotalAssets() (v int64) {
	return p.TotalAssets
}

func (p *GetAssetStatsResponse) GetTotalModels() (v int64) {
	return p.TotalModels
}

func (p *GetAssetStatsResponse) GetTotalPresets() (v int64) {
	return p.TotalPresets
}

func (p *GetAssetStatsResponse) GetTotalStorageBytes() (v int64) {
	return p.TotalStorageBytes
}
func (p *GetAssetStatsResponse) SetTotalAssets(val int64) {
	p.TotalAssets = val
}
func (p *GetAssetStatsResponse) SetTotalModels(val int64) {
	p.TotalModels = val
}
func (p *GetAssetStatsResponse) SetTotalPresets(val int64) {
	p.TotalPresets = val
}
func (p *GetAssetStatsResponse) SetTotalStorageBytes(val int64) {
	p.TotalStorageBytes = val
}

func (p *GetAssetStatsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAssetStatsResponse(%+v)", *p)
}

var fieldIDToName_GetAssetStatsResponse = map[int16]string{
	1: "total_assets",
	2: "total_models",
	3: "total_presets",
	4: "total_storage_bytes",
}

type AssetServiceV0_1 interface {
	ListAssets(ctx context.Context, request *ListAssetsRequest) (r *ListAssetsResponse, err error)

	RegisterAsset(ctx context.Context, request *RegisterAssetRequest) (r *RegisterAssetResponse, err error)

	DeleteAsset(ctx context.Context, request *DeleteAssetRequest) (r *DeleteAssetResponse, err error)

	GetAssetStats(ctx context.Context, request *GetAssetStatsRequest) (r *GetAssetStatsResponse, err error)
}

type AssetServiceV0_1ListAssetsArgs struct {
	Request *ListAssetsRequest `thrift:"request,1" frugal:"1,default,ListAssetsRequest" json:"request"`
}

func NewAssetServiceV0_1ListAssetsArgs() *AssetServiceV0_1ListAssetsArgs {
	return &AssetServiceV0_1ListAssetsArgs{}
}

func (p *AssetServiceV0_1ListAssetsArgs) InitDefault() {
}

var AssetServiceV0_1ListAssetsArgs_Request_DEFAULT *ListAssetsRequest

func (p *AssetServiceV0_1ListAssetsArgs) GetRequest() (v *ListAssetsRequest) {
	if !p.IsSetRequest() {
		return AssetServiceV0_1ListAssetsArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AssetServiceV0_1ListAssetsArgs) SetRequest(val *ListAssetsRequest) {
	p.Request = val
}

func (p *AssetServiceV0_1ListAssetsArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AssetServiceV0_1ListAssetsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AssetServiceV0_1ListAssetsArgs(%+v)", *p)
}

var fieldIDToName_AssetServiceV0_1ListAssetsArgs = map[int16]string{
	1: "request",
}

type AssetServiceV0_1ListAssetsResult struct {
	Success *ListAssetsResponse `thrift:"success,0,optional" frugal:"0,optional,ListAssetsResponse" json:"success,omitempty"`
}

func NewAssetServiceV0_1ListAssetsResult() *AssetServiceV0_1ListAssetsResult {
	return &AssetServiceV0_1ListAssetsResult{}
}

func (p *AssetServiceV0_1ListAssetsResult) InitDefault() {
}

var AssetServiceV0_1ListAssetsResult_Success_DEFAULT *ListAssetsResponse

func (p *AssetServiceV0_1ListAssetsResult) GetSuccess() (v *ListAssetsResponse) {
	if !p.IsSetSuccess() {
		return AssetServiceV0_1ListAssetsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AssetServiceV0_1ListAssetsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListAssetsResponse)
}

func (p *AssetServiceV0_1ListAssetsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AssetServiceV0_1ListAssetsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AssetServiceV0_1ListAssetsResult(%+v)", *p)
}

var fieldIDToName_AssetServiceV0_1ListAssetsResult = map[int16]string{
	0: "success",
}

type AssetServiceV0_1RegisterAssetArgs struct {
	Request *RegisterAssetRequest `thrift:"request,1" frugal:"1,default,RegisterAssetRequest" json:"request"`
}

func NewAssetServiceV0_1RegisterAssetArgs() *AssetServiceV0_1RegisterAssetArgs {
	return &AssetServiceV0_1RegisterAssetArgs{}
}

func (p *AssetServiceV0_1RegisterAssetArgs) InitDefault() {
}

var AssetServiceV0_1RegisterAssetArgs_Request_DEFAULT *RegisterAssetRequest

func (p *AssetServiceV0_1RegisterAssetArgs) GetRequest() (v *RegisterAssetRequest) {
	if !p.IsSetRequest() {
		return AssetServiceV0_1RegisterAssetArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AssetServiceV0_1RegisterAssetArgs) SetRequest(val *RegisterAssetRequest) {
	p.Request = val
}

func (p *AssetServiceV0_1RegisterAssetArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AssetServiceV0_1RegisterAssetArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AssetServiceV0_1RegisterAssetArgs(%+v)", *p)
}

var fieldIDToName_AssetServiceV0_1RegisterAssetArgs = map[int16]string{
	1: "request",
}

type AssetServiceV0_1RegisterAssetResult struct {
	Success *RegisterAssetResponse `thrift:"success,0,optional" frugal:"0,optional,RegisterAssetResponse" json:"success,omitempty"`
}

func NewAssetServiceV0_1RegisterAssetResult() *AssetServiceV0_1RegisterAssetResult {
	return &AssetServiceV0_1RegisterAssetResult{}
}

func (p *AssetServiceV0_1RegisterAssetResult) InitDefault() {
}

var AssetServiceV0_1RegisterAssetResult_Success_DEFAULT *RegisterAssetResponse

func (p *AssetServiceV0_1RegisterAssetResult) GetSuccess() (v *RegisterAssetResponse) {
	if !p.IsSetSuccess() {
		return AssetServiceV0_1RegisterAssetResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AssetServiceV0_1RegisterAssetResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterAssetResponse)
}

func (p *AssetServiceV0_1RegisterAssetResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AssetServiceV0_1RegisterAssetResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AssetServiceV0_1RegisterAssetResult(%+v)", *p)
}

var fieldIDToName_AssetServiceV0_1RegisterAssetResult = map[int16]string{
	0: "success",
}

type AssetServiceV0_1DeleteAssetArgs struct {
	Request *DeleteAssetRequest `thrift:"request,1" frugal:"1,default,DeleteAssetRequest" json:"request"`
}

func NewAssetServiceV0_1DeleteAssetArgs() *AssetServiceV0_1DeleteAssetArgs {
	return &AssetServiceV0_1DeleteAssetArgs{}
}

func (p *AssetServiceV0_1DeleteAssetArgs) InitDefault() {
}

var AssetServiceV0_1DeleteAssetArgs_Request_DEFAULT *DeleteAssetRequest

func (p *AssetServiceV0_1DeleteAssetArgs) GetRequest() (v *DeleteAssetRequest) {
	if !p.IsSetRequest() {
		return AssetServiceV0_1DeleteAssetArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AssetServiceV0_1DeleteAssetArgs) SetRequest(val *DeleteAssetRequest) {
	p.Request = val
}

func (p *AssetServiceV0_1DeleteAssetArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AssetServiceV0_1DeleteAssetArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AssetServiceV0_1DeleteAssetArgs(%+v)", *p)
}

var fieldIDToName_AssetServiceV0_1DeleteAssetArgs = map[int16]string{
	1: "request",
}

type AssetServiceV0_1DeleteAssetResult struct {
	Success *DeleteAssetResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteAssetResponse" json:"success,omitempty"`
}

func NewAssetServiceV0_1DeleteAssetResult() *AssetServiceV0_1DeleteAssetResult {
	return &AssetServiceV0_1DeleteAssetResult{}
}

func (p *AssetServiceV0_1DeleteAssetResult) InitDefault() {
}

var AssetServiceV0_1DeleteAssetResult_Success_DEFAULT *DeleteAssetResponse

func (p *AssetServiceV0_1DeleteAssetResult) GetSuccess() (v *DeleteAssetResponse) {
	if !p.IsSetSuccess() {
		return AssetServiceV0_1DeleteAssetResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AssetServiceV0_1DeleteAssetResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteAssetResponse)
}

func (p *AssetServiceV0_1DeleteAssetResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AssetServiceV0_1DeleteAssetResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AssetServiceV0_1DeleteAssetResult(%+v)", *p)
}

var fieldIDToName_AssetServiceV0_1DeleteAssetResult = map[int16]string{
	0: "success",
}

type AssetServiceV0_1GetAssetStatsArgs struct {
	Request *GetAssetStatsRequest `thrift:"request,1" frugal:"1,default,GetAssetStatsRequest" json:"request"`
}

func NewAssetServiceV0_1GetAssetStatsArgs() *AssetServiceV0_1GetAssetStatsArgs {
	return &AssetServiceV0_1GetAssetStatsArgs{}
}

func (p *AssetServiceV0_1GetAssetStatsArgs) InitDefault() {
}

var AssetServiceV0_1GetAssetStatsArgs_Request_DEFAULT *GetAssetStatsRequest

func (p *AssetServiceV0_1GetAssetStatsArgs) GetRequest() (v *GetAssetStatsRequest) {
	if !p.IsSetRequest() {
		return AssetServiceV0_1GetAssetStatsArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AssetServiceV0_1GetAssetStatsArgs) SetRequest(val *GetAssetStatsRequest) {
	p.Request = val
}

func (p *AssetServiceV0_1GetAssetStatsArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AssetServiceV0_1GetAssetStatsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AssetServiceV0_1GetAssetStatsArgs(%+v)", *p)
}

var fieldIDToName_AssetServiceV0_1GetAssetStatsArgs = map[int16]string{
	1: "request",
}

type AssetServiceV0_1GetAssetStatsResult struct {
	Success *GetAssetStatsResponse `thrift:"success,0,optional" frugal:"0,optional,GetAssetStatsResponse" json:"success,omitempty"`
}

func NewAssetServiceV0_1GetAssetStatsResult() *AssetServiceV0_1GetAssetStatsResult {
	return &AssetServiceV0_1GetAssetStatsResult{}
}

func (p *AssetServiceV0_1GetAssetStatsResult) InitDefault() {
}

var AssetServiceV0_1GetAssetStatsResult_Success_DEFAULT *GetAssetStatsResponse

func (p *AssetServiceV0_1GetAssetStatsResult) GetSuccess() (v *GetAssetStatsResponse) {
	if !p.IsSetSuccess() {
		return AssetServiceV0_1GetAssetStatsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AssetServiceV0_1GetAssetStatsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAssetStatsResponse)
}

func (p *AssetServiceV0_1GetAssetStatsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AssetServiceV0_1GetAssetStatsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AssetServiceV0_1GetAssetStatsResult(%+v)", *p)
}

var fieldIDToName_AssetServiceV0_1GetAssetStatsResult = map[int16]string{
	0: "success",
}
