// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package v0_1

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type LLMProvider int64

const (
	LLMProvider_OPENAI    LLMProvider = 1
	LLMProvider_ANTHROPIC LLMProvider = 2
)

func (p LLMProvider) String() string {
	switch p {
	case LLMProvider_OPENAI:
		return "OPENAI"
	case LLMProvider_ANTHROPIC:
		return "ANTHROPIC"
	}
	return "<UNSET>"
}

func LLMProviderFromString(s string) (LLMProvider, error) {
	switch s {
	case "OPENAI":
		return LLMProvider_OPENAI, nil
	case "ANTHROPIC":
		return LLMProvider_ANTHROPIC, nil
	}
	return LLMProvider(0), fmt.Errorf("not a valid LLMProvider string")
}

func LLMProviderPtr(v LLMProvider) *LLMProvider { return &v }
func (p *LLMProvider) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = LLMProvider(result.Int64)
	return
}

func (p *LLMProvider) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type LLMKeyOperation int64

const (
	LLMKeyOperation_SAVE   LLMKeyOperation = 1
	LLMKeyOperation_UPDATE LLMKeyOperation = 2
	LLMKeyOperation_DELETE LLMKeyOperation = 3
)

func (p LLMKeyOperation) String() string {
	switch p {
	case LLMKeyOperation_SAVE:
		return "SAVE"
	case LLMKeyOperation_UPDATE:
		return "UPDATE"
	case LLMKeyOperation_DELETE:
		return "DELETE"
	}
	return "<UNSET>"
}

func LLMKeyOperationFromString(s string) (LLMKeyOperation, error) {
	switch s {
	case "SAVE":
		return LLMKeyOperation_SAVE, nil
	case "UPDATE":
		return LLMKeyOperation_UPDATE, nil
	case "DELETE":
		return LLMKeyOperation_DELETE, nil
	}
	return LLMKeyOperation(0), fmt.Errorf("not a valid LLMKeyOperation string")
}

func LLMKeyOperationPtr(v LLMKeyOperation) *LLMKeyOperation { return &v }
func (p *LLMKeyOperation) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = LLMKeyOperation(result.Int64)
	return
}

func (p *LLMKeyOperation) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ManageLLMKeyRequest struct {
	UserId    string          `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
	Operation LLMKeyOperation `thrift:"operation,2,required" frugal:"2,required,LLMKeyOperation" json:"operation"`
	KeyId     *string         `thrift:"key_id,3,optional" frugal:"3,optional,string" json:"key_id,omitempty"`
	Provider  *LLMProvider    `thrift:"provider,4,optional" frugal:"4,optional,LLMProvider" json:"provider,omitempty"`
	Name      *string         `thrift:"name,5,optional" frugal:"5,optional,string" json:"name,omitempty"`
	ApiKey    *string         `thrift:"api_key,6,optional" frugal:"6,optional,string" json:"api_key,omitempty"`
	BaseUrl   *string         `thrift:"base_url,7,optional" frugal:"7,optional,string" json:"base_url,omitempty"`
}

func NewManageLLMKeyRequest() *ManageLLMKeyRequest {
	return &ManageLLMKeyRequest{}
}

func (p *ManageLLMKeyRequest) InitDefault() {
}

func (p *ManageLLMKeyRequest) GetUserId() (v string) {
	return p.UserId
}

func (p *ManageLLMKeyRequest) GetOperation() (v LLMKeyOperation) {
	return p.Operation
}

var ManageLLMKeyRequest_KeyId_DEFAULT string

func (p *ManageLLMKeyRequest) GetKeyId() (v string) {
	if !p.IsSetKeyId() {
		return ManageLLMKeyRequest_KeyId_DEFAULT
	}
	return *p.KeyId
}

var ManageLLMKeyRequest_Provider_DEFAULT LLMProvider

func (p *ManageLLMKeyRequest) GetProvider() (v LLMProvider) {
	if !p.IsSetProvider() {
		return ManageLLMKeyRequest_Provider_DEFAULT
	}
	return *p.Provider
}

var ManageLLMKeyRequest_Name_DEFAULT string

func (p *ManageLLMKeyRequest) GetName() (v string) {
	if !p.IsSetName() {
		return ManageLLMKeyRequest_Name_DEFAULT
	}
	return *p.Name
}

var ManageLLMKeyRequest_ApiKey_DEFAULT string

func (p *ManageLLMKeyRequest) GetApiKey() (v string) {
	if !p.IsSetApiKey() {
		return ManageLLMKeyRequest_ApiKey_DEFAULT
	}
	return *p.ApiKey
}

var ManageLLMKeyRequest_BaseUrl_DEFAULT string

func (p *ManageLLMKeyRequest) GetBaseUrl() (v string) {
	if !p.IsSetBaseUrl() {
		return ManageLLMKeyRequest_BaseUrl_DEFAULT
	}
	return *p.BaseUrl
}
func (p *ManageLLMKeyRequest) SetUserId(val string) {
	p.UserId = val
}
func (p *ManageLLMKeyRequest) SetOperation(val LLMKeyOperation) {
	p.Operation = val
}
func (p *ManageLLMKeyRequest) SetKeyId(val *string) {
	p.KeyId = val
}
func (p *ManageLLMKeyRequest) SetProvider(val *LLMProvider) {
	p.Provider = val
}
func (p *ManageLLMKeyRequest) SetName(val *string) {
	p.Name = val
}
func (p *ManageLLMKeyRequest) SetApiKey(val *string) {
	p.ApiKey = val
}
func (p *ManageLLMKeyRequest) SetBaseUrl(val *string) {
	p.BaseUrl = val
}

func (p *ManageLLMKeyRequest) IsSetKeyId() bool {
	return p.KeyId != nil
}

func (p *ManageLLMKeyRequest) IsSetProvider() bool {
	return p.Provider != nil
}

func (p *ManageLLMKeyRequest) IsSetName() bool {
	return p.Name != nil
}

func (p *ManageLLMKeyRequest) IsSetApiKey() bool {
	return p.ApiKey != nil
}

func (p *ManageLLMKeyRequest) IsSetBaseUrl() bool {
	return p.BaseUrl != nil
}

func (p *ManageLLMKeyRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ManageLLMKeyRequest(%+v)", *p)
}

var fieldIDToName_ManageLLMKeyRequest = map[int16]string{
	1: "user_id",
	2: "operation",
	3: "key_id",
	4: "provider",
	5: "name",
	6: "api_key",
	7: "base_url",
}

type ManageLLMKeyResponse struct {
	KeyId    string       `thrift:"key_id,1,required" frugal:"1,required,string" json:"key_id"`
	Provider *LLMProvider `thrift:"provider,2,optional" frugal:"2,optional,LLMProvider" json:"provider,omitempty"`
}

func NewManageLLMKeyResponse() *ManageLLMKeyResponse {
	return &ManageLLMKeyResponse{}
}

func (p *ManageLLMKeyResponse) InitDefault() {
}

func (p *ManageLLMKeyResponse) GetKeyId() (v string) {
	return p.KeyId
}

var ManageLLMKeyResponse_Provider_DEFAULT LLMProvider

func (p *ManageLLMKeyResponse) GetProvider() (v LLMProvider) {
	if !p.IsSetProvider() {
		return ManageLLMKeyResponse_Provider_DEFAULT
	}
	return *p.Provider
}
func (p *ManageLLMKeyResponse) SetKeyId(val string) {
	p.KeyId = val
}
func (p *ManageLLMKeyResponse) SetProvider(val *LLMProvider) {
	p.Provider = val
}

func (p *ManageLLMKeyResponse) IsSetProvider() bool {
	return p.Provider != nil
}

func (p *ManageLLMKeyResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ManageLLMKeyResponse(%+v)", *p)
}

var fieldIDToName_ManageLLMKeyResponse = map[int16]string{
	1: "key_id",
	2: "provider",
}

type LLMKeyServiceV0_1 interface {
	ManageLLMKey(ctx context.Context, request *ManageLLMKeyRequest) (r *ManageLLMKeyResponse, err error)
}

type LLMKeyServiceV0_1ManageLLMKeyArgs struct {
	Request *ManageLLMKeyRequest `thrift:"request,1" frugal:"1,default,ManageLLMKeyRequest" json:"request"`
}

func NewLLMKeyServiceV0_1ManageLLMKeyArgs() *LLMKeyServiceV0_1ManageLLMKeyArgs {
	return &LLMKeyServiceV0_1ManageLLMKeyArgs{}
}

func (p *LLMKeyServiceV0_1ManageLLMKeyArgs) InitDefault() {
}

var LLMKeyServiceV0_1ManageLLMKeyArgs_Request_DEFAULT *ManageLLMKeyRequest

func (p *LLMKeyServiceV0_1ManageLLMKeyArgs) GetRequest() (v *ManageLLMKeyRequest) {
	if !p.IsSetRequest() {
		return LLMKeyServiceV0_1ManageLLMKeyArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *LLMKeyServiceV0_1ManageLLMKeyArgs) SetRequest(val *ManageLLMKeyRequest) {
	p.Request = val
}

func (p *LLMKeyServiceV0_1ManageLLMKeyArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *LLMKeyServiceV0_1ManageLLMKeyArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LLMKeyServiceV0_1ManageLLMKeyArgs(%+v)", *p)
}

var fieldIDToName_LLMKeyServiceV0_1ManageLLMKeyArgs = map[int16]string{
	1: "request",
}

type LLMKeyServiceV0_1ManageLLMKeyResult struct {
	Success *ManageLLMKeyResponse `thrift:"success,0,optional" frugal:"0,optional,ManageLLMKeyResponse" json:"success,omitempty"`
}

func NewLLMKeyServiceV0_1ManageLLMKeyResult() *LLMKeyServiceV0_1ManageLLMKeyResult {
	return &LLMKeyServiceV0_1ManageLLMKeyResult{}
}

func (p *LLMKeyServiceV0_1ManageLLMKeyResult) InitDefault() {
}

var LLMKeyServiceV0_1ManageLLMKeyResult_Success_DEFAULT *ManageLLMKeyResponse

func (p *LLMKeyServiceV0_1ManageLLMKeyResult) GetSuccess() (v *ManageLLMKeyResponse) {
	if !p.IsSetSuccess() {
		return LLMKeyServiceV0_1ManageLLMKeyResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LLMKeyServiceV0_1ManageLLMKeyResult) SetSuccess(x interface{}) {
	p.Success = x.(*ManageLLMKeyResponse)
}

func (p *LLMKeyServiceV0_1ManageLLMKeyResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LLMKeyServiceV0_1ManageLLMKeyResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LLMKeyServiceV0_1ManageLLMKeyResult(%+v)", *p)
}

var fieldIDToName_LLMKeyServiceV0_1ManageLLMKeyResult = map[int16]string{
	0: "success",
}
