// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package v0_1

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type TaskStatus int64

const (
	TaskStatus_ACCEPTED TaskStatus = 1
	TaskStatus_REJECTED TaskStatus = 2
)

func (p TaskStatus) String() string {
	switch p {
	case TaskStatus_ACCEPTED:
		return "ACCEPTED"
	case TaskStatus_REJECTED:
		return "REJECTED"
	}
	return "<UNSET>"
}

func TaskStatusFromString(s string) (TaskStatus, error) {
	switch s {
	case "ACCEPTED":
		return TaskStatus_ACCEPTED, nil
	case "REJECTED":
		return TaskStatus_REJECTED, nil
	}
	return TaskStatus(0), fmt.Errorf("not a valid TaskStatus string")
}

func TaskStatusPtr(v TaskStatus) *TaskStatus { return &v }
func (p *TaskStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TaskStatus(result.Int64)
	return
}

func (p *TaskStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type CreateShotPreviewTaskRequest struct {
	UserId         string  `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
	Prompt         string  `thrift:"prompt,2,required" frugal:"2,required,string" json:"prompt"`
	ConversationId *string `thrift:"conversation_id,3,optional" frugal:"3,optional,string" json:"conversation_id,omitempty"`
	RequestId      *string `thrift:"request_id,4,optional" frugal:"4,optional,string" json:"request_id,omitempty"`
}

func NewCreateShotPreviewTaskRequest() *CreateShotPreviewTaskRequest {
	return &CreateShotPreviewTaskRequest{}
}

func (p *CreateShotPreviewTaskRequest) InitDefault() {
}

func (p *CreateShotPreviewTaskRequest) GetUserId() (v string) {
	return p.UserId
}

func (p *CreateShotPreviewTaskRequest) GetPrompt() (v string) {
	return p.Prompt
}

var CreateShotPreviewTaskRequest_ConversationId_DEFAULT string

func (p *CreateShotPreviewTaskRequest) GetConversationId() (v string) {
	if !p.IsSetConversationId() {
		return CreateShotPreviewTaskRequest_ConversationId_DEFAULT
	}
	return *p.ConversationId
}

var CreateShotPreviewTaskRequest_RequestId_DEFAULT string

func (p *CreateShotPreviewTaskRequest) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return CreateShotPreviewTaskRequest_RequestId_DEFAULT
	}
	return *p.RequestId
}
func (p *CreateShotPreviewTaskRequest) SetUserId(val string) {
	p.UserId = val
}
func (p *CreateShotPreviewTaskRequest) SetPrompt(val string) {
	p.Prompt = val
}
func (p *CreateShotPreviewTaskRequest) SetConversationId(val *string) {
	p.ConversationId = val
}
func (p *CreateShotPreviewTaskRequest) SetRequestId(val *string) {
	p.RequestId = val
}

func (p *CreateShotPreviewTaskRequest) IsSetConversationId() bool {
	return p.ConversationId != nil
}

func (p *CreateShotPreviewTaskRequest) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *CreateShotPreviewTaskRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateShotPreviewTaskRequest(%+v)", *p)
}

var fieldIDToName_CreateShotPreviewTaskRequest = map[int16]string{
	1: "user_id",
	2: "prompt",
	3: "conversation_id",
	4: "request_id",
}

type CreateShotPreviewTaskResponse struct {
	TaskId    string     `thrift:"task_id,1,required" frugal:"1,required,string" json:"task_id"`
	Status    TaskStatus `thrift:"status,2,required" frugal:"2,required,TaskStatus" json:"status"`
	RequestId *string    `thrift:"request_id,3,optional" frugal:"3,optional,string" json:"request_id,omitempty"`
}

func NewCreateShotPreviewTaskResponse() *CreateShotPreviewTaskResponse {
	return &CreateShotPreviewTaskResponse{}
}

func (p *CreateShotPreviewTaskResponse) InitDefault() {
}

func (p *CreateShotPreviewTaskResponse) GetTaskId() (v string) {
	return p.TaskId
}

func (p *CreateShotPreviewTaskResponse) GetStatus() (v TaskStatus) {
	return p.Status
}

var CreateShotPreviewTaskResponse_RequestId_DEFAULT string

func (p *CreateShotPreviewTaskResponse) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return CreateShotPreviewTaskResponse_RequestId_DEFAULT
	}
	return *p.RequestId
}
func (p *CreateShotPreviewTaskResponse) SetTaskId(val string) {
	p.TaskId = val
}
func (p *CreateShotPreviewTaskResponse) SetStatus(val TaskStatus) {
	p.Status = val
}
func (p *CreateShotPreviewTaskResponse) SetRequestId(val *string) {
	p.RequestId = val
}

func (p *CreateShotPreviewTaskResponse) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *CreateShotPreviewTaskResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateShotPreviewTaskResponse(%+v)", *p)
}

var fieldIDToName_CreateShotPreviewTaskResponse = map[int16]string{
	1: "task_id",
	2: "status",
	3: "request_id",
}

type ShotPreviewServiceV0_1 interface {
	CreateShotPreviewTask(ctx context.Context, request *CreateShotPreviewTaskRequest) (r *CreateShotPreviewTaskResponse, err error)
}

type ShotPreviewServiceV0_1CreateShotPreviewTaskArgs struct {
	Request *CreateShotPreviewTaskRequest `thrift:"request,1" frugal:"1,default,CreateShotPreviewTaskRequest" json:"request"`
}

func NewShotPreviewServiceV0_1CreateShotPreviewTaskArgs() *ShotPreviewServiceV0_1CreateShotPreviewTaskArgs {
	return &ShotPreviewServiceV0_1CreateShotPreviewTaskArgs{}
}

func (p *ShotPreviewServiceV0_1CreateShotPreviewTaskArgs) InitDefault() {
}

var ShotPreviewServiceV0_1CreateShotPreviewTaskArgs_Request_DEFAULT *CreateShotPreviewTaskRequest

func (p *ShotPreviewServiceV0_1CreateShotPreviewTaskArgs) GetRequest() (v *CreateShotPreviewTaskRequest) {
	if !p.IsSetRequest() {
		return ShotPreviewServiceV0_1CreateShotPreviewTaskArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *ShotPreviewServiceV0_1CreateShotPreviewTaskArgs) SetRequest(val *CreateShotPreviewTaskRequest) {
	p.Request = val
}

func (p *ShotPreviewServiceV0_1CreateShotPreviewTaskArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *ShotPreviewServiceV0_1CreateShotPreviewTaskArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ShotPreviewServiceV0_1CreateShotPreviewTaskArgs(%+v)", *p)
}

var fieldIDToName_ShotPreviewServiceV0_1CreateShotPreviewTaskArgs = map[int16]string{
	1: "request",
}

type ShotPreviewServiceV0_1CreateShotPreviewTaskResult struct {
	Success *CreateShotPreviewTaskResponse `thrift:"success,0,optional" frugal:"0,optional,CreateShotPreviewTaskResponse" json:"success,omitempty"`
}

func NewShotPreviewServiceV0_1CreateShotPreviewTaskResult() *ShotPreviewServiceV0_1CreateShotPreviewTaskResult {
	return &ShotPreviewServiceV0_1CreateShotPreviewTaskResult{}
}

func (p *ShotPreviewServiceV0_1CreateShotPreviewTaskResult) InitDefault() {
}

var ShotPreviewServiceV0_1CreateShotPreviewTaskResult_Success_DEFAULT *CreateShotPreviewTaskResponse

func (p *ShotPreviewServiceV0_1CreateShotPreviewTaskResult) GetSuccess() (v *CreateShotPreviewTaskResponse) {
	if !p.IsSetSuccess() {
		return ShotPreviewServiceV0_1CreateShotPreviewTaskResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ShotPreviewServiceV0_1CreateShotPreviewTaskResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateShotPreviewTaskResponse)
}

func (p *ShotPreviewServiceV0_1CreateShotPreviewTaskResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ShotPreviewServiceV0_1CreateShotPreviewTaskResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ShotPreviewServiceV0_1CreateShotPreviewTaskResult(%+v)", *p)
}

var fieldIDToName_ShotPreviewServiceV0_1CreateShotPreviewTaskResult = map[int16]string{
	0: "success",
}
