// Code generated by Kitex v0.16.0. DO NOT EDIT.

package assetservicev0_1

import (
	"context"
	"errors"
	v0_1 "github.com/S-zhi/blender-shot-preview/kitex_gen/handler/v0_1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListAssets": kitex.NewMethodInfo(
		listAssetsHandler,
		newAssetServiceV0_1ListAssetsArgs,
		newAssetServiceV0_1ListAssetsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RegisterAsset": kitex.NewMethodInfo(
		registerAssetHandler,
		newAssetServiceV0_1RegisterAssetArgs,
		newAssetServiceV0_1RegisterAssetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteAsset": kitex.NewMethodInfo(
		deleteAssetHandler,
		newAssetServiceV0_1DeleteAssetArgs,
		newAssetServiceV0_1DeleteAssetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAssetStats": kitex.NewMethodInfo(
		getAssetStatsHandler,
		newAssetServiceV0_1GetAssetStatsArgs,
		newAssetServiceV0_1GetAssetStatsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	assetServiceV0_1ServiceInfo                = NewServiceInfo()
	assetServiceV0_1ServiceInfoForClient       = NewServiceInfoForClient()
	assetServiceV0_1ServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return assetServiceV0_1ServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return assetServiceV0_1ServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return assetServiceV0_1ServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AssetServiceV0_1"
	handlerType := (*v0_1.AssetServiceV0_1)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "v0_1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.0",
		Extra:           extra,
	}
	return svcInfo
}

func listAssetsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*v0_1.AssetServiceV0_1ListAssetsArgs)
	realResult := result.(*v0_1.AssetServiceV0_1ListAssetsResult)
	success, err := handler.(v0_1.AssetServiceV0_1).ListAssets(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceV0_1ListAssetsArgs() interface{} {
	return v0_1.NewAssetServiceV0_1ListAssetsArgs()
}

func newAssetServiceV0_1ListAssetsResult() interface{} {
	return v0_1.NewAssetServiceV0_1ListAssetsResult()
}

func registerAssetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*v0_1.AssetServiceV0_1RegisterAssetArgs)
	realResult := result.(*v0_1.AssetServiceV0_1RegisterAssetResult)
	success, err := handler.(v0_1.AssetServiceV0_1).RegisterAsset(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceV0_1RegisterAssetArgs() interface{} {
	return v0_1.NewAssetServiceV0_1RegisterAssetArgs()
}

func newAssetServiceV0_1RegisterAssetResult() interface{} {
	return v0_1.NewAssetServiceV0_1RegisterAssetResult()
}

func deleteAssetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*v0_1.AssetServiceV0_1DeleteAssetArgs)
	realResult := result.(*v0_1.AssetServiceV0_1DeleteAssetResult)
	success, err := handler.(v0_1.AssetServiceV0_1).DeleteAsset(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceV0_1DeleteAssetArgs() interface{} {
	return v0_1.NewAssetServiceV0_1DeleteAssetArgs()
}

func newAssetServiceV0_1DeleteAssetResult() interface{} {
	return v0_1.NewAssetServiceV0_1DeleteAssetResult()
}

func getAssetStatsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*v0_1.AssetServiceV0_1GetAssetStatsArgs)
	realResult := result.(*v0_1.AssetServiceV0_1GetAssetStatsResult)
	success, err := handler.(v0_1.AssetServiceV0_1).GetAssetStats(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceV0_1GetAssetStatsArgs() interface{} {
	return v0_1.NewAssetServiceV0_1GetAssetStatsArgs()
}

func newAssetServiceV0_1GetAssetStatsResult() interface{} {
	return v0_1.NewAssetServiceV0_1GetAssetStatsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListAssets(ctx context.Context, request *v0_1.ListAssetsRequest) (r *v0_1.ListAssetsResponse, err error) {
	var _args v0_1.AssetServiceV0_1ListAssetsArgs
	_args.Request = request
	var _result v0_1.AssetServiceV0_1ListAssetsResult
	if err = p.c.Call(ctx, "ListAssets", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RegisterAsset(ctx context.Context, request *v0_1.RegisterAssetRequest) (r *v0_1.RegisterAssetResponse, err error) {
	var _args v0_1.AssetServiceV0_1RegisterAssetArgs
	_args.Request = request
	var _result v0_1.AssetServiceV0_1RegisterAssetResult
	if err = p.c.Call(ctx, "RegisterAsset", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteAsset(ctx context.Context, request *v0_1.DeleteAssetRequest) (r *v0_1.DeleteAssetResponse, err error) {
	var _args v0_1.AssetServiceV0_1DeleteAssetArgs
	_args.Request = request
	var _result v0_1.AssetServiceV0_1DeleteAssetResult
	if err = p.c.Call(ctx, "DeleteAsset", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAssetStats(ctx context.Context, request *v0_1.GetAssetStatsRequest) (r *v0_1.GetAssetStatsResponse, err error) {
	var _args v0_1.AssetServiceV0_1GetAssetStatsArgs
	_args.Request = request
	var _result v0_1.AssetServiceV0_1GetAssetStatsResult
	if err = p.c.Call(ctx, "GetAssetStats", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
