// Code generated by Kitex v0.16.0. DO NOT EDIT.

package assetservicev0_1

import (
	"context"
	v0_1 "github.com/S-zhi/blender-shot-preview/kitex_gen/handler/v0_1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListAssets(ctx context.Context, request *v0_1.ListAssetsRequest, callOptions ...callopt.Option) (r *v0_1.ListAssetsResponse, err error)
	RegisterAsset(ctx context.Context, request *v0_1.RegisterAssetRequest, callOptions ...callopt.Option) (r *v0_1.RegisterAssetResponse, err error)
	DeleteAsset(ctx context.Context, request *v0_1.DeleteAssetRequest, callOptions ...callopt.Option) (r *v0_1.DeleteAssetResponse, err error)
	GetAssetStats(ctx context.Context, request *v0_1.GetAssetStatsRequest, callOptions ...callopt.Option) (r *v0_1.GetAssetStatsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAssetServiceV0_1Client{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAssetServiceV0_1Client struct {
	*kClient
}

func (p *kAssetServiceV0_1Client) ListAssets(ctx context.Context, request *v0_1.ListAssetsRequest, callOptions ...callopt.Option) (r *v0_1.ListAssetsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAssets(ctx, request)
}

func (p *kAssetServiceV0_1Client) RegisterAsset(ctx context.Context, request *v0_1.RegisterAssetRequest, callOptions ...callopt.Option) (r *v0_1.RegisterAssetResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegisterAsset(ctx, request)
}

func (p *kAssetServiceV0_1Client) DeleteAsset(ctx context.Context, request *v0_1.DeleteAssetRequest, callOptions ...callopt.Option) (r *v0_1.DeleteAssetResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteAsset(ctx, request)
}

func (p *kAssetServiceV0_1Client) GetAssetStats(ctx context.Context, request *v0_1.GetAssetStatsRequest, callOptions ...callopt.Option) (r *v0_1.GetAssetStatsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAssetStats(ctx, request)
}
