// Code generated by Kitex v0.16.0. DO NOT EDIT.

package shotpreviewservicev0_1

import (
	"context"
	v0_1 "github.com/S-zhi/blender-shot-preview/kitex_gen/handler/v0_1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateShotPreviewTask(ctx context.Context, request *v0_1.CreateShotPreviewTaskRequest, callOptions ...callopt.Option) (r *v0_1.CreateShotPreviewTaskResponse, err error)
	GetShotPreviewTask(ctx context.Context, request *v0_1.GetShotPreviewTaskRequest, callOptions ...callopt.Option) (r *v0_1.GetShotPreviewTaskResponse, err error)
	CancelShotPreviewTask(ctx context.Context, request *v0_1.CancelShotPreviewTaskRequest, callOptions ...callopt.Option) (r *v0_1.CancelShotPreviewTaskResponse, err error)
	RetryShotPreviewTask(ctx context.Context, request *v0_1.RetryShotPreviewTaskRequest, callOptions ...callopt.Option) (r *v0_1.RetryShotPreviewTaskResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kShotPreviewServiceV0_1Client{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kShotPreviewServiceV0_1Client struct {
	*kClient
}

func (p *kShotPreviewServiceV0_1Client) CreateShotPreviewTask(ctx context.Context, request *v0_1.CreateShotPreviewTaskRequest, callOptions ...callopt.Option) (r *v0_1.CreateShotPreviewTaskResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateShotPreviewTask(ctx, request)
}

func (p *kShotPreviewServiceV0_1Client) GetShotPreviewTask(ctx context.Context, request *v0_1.GetShotPreviewTaskRequest, callOptions ...callopt.Option) (r *v0_1.GetShotPreviewTaskResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetShotPreviewTask(ctx, request)
}

func (p *kShotPreviewServiceV0_1Client) CancelShotPreviewTask(ctx context.Context, request *v0_1.CancelShotPreviewTaskRequest, callOptions ...callopt.Option) (r *v0_1.CancelShotPreviewTaskResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelShotPreviewTask(ctx, request)
}

func (p *kShotPreviewServiceV0_1Client) RetryShotPreviewTask(ctx context.Context, request *v0_1.RetryShotPreviewTaskRequest, callOptions ...callopt.Option) (r *v0_1.RetryShotPreviewTaskResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RetryShotPreviewTask(ctx, request)
}
