// Code generated by Kitex v0.16.0. DO NOT EDIT.

package shotpreviewservicev0_1

import (
	"context"
	"errors"
	v0_1 "github.com/S-zhi/blender-shot-preview/kitex_gen/handler/v0_1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateShotPreviewTask": kitex.NewMethodInfo(
		createShotPreviewTaskHandler,
		newShotPreviewServiceV0_1CreateShotPreviewTaskArgs,
		newShotPreviewServiceV0_1CreateShotPreviewTaskResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetShotPreviewTask": kitex.NewMethodInfo(
		getShotPreviewTaskHandler,
		newShotPreviewServiceV0_1GetShotPreviewTaskArgs,
		newShotPreviewServiceV0_1GetShotPreviewTaskResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CancelShotPreviewTask": kitex.NewMethodInfo(
		cancelShotPreviewTaskHandler,
		newShotPreviewServiceV0_1CancelShotPreviewTaskArgs,
		newShotPreviewServiceV0_1CancelShotPreviewTaskResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RetryShotPreviewTask": kitex.NewMethodInfo(
		retryShotPreviewTaskHandler,
		newShotPreviewServiceV0_1RetryShotPreviewTaskArgs,
		newShotPreviewServiceV0_1RetryShotPreviewTaskResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	shotPreviewServiceV0_1ServiceInfo                = NewServiceInfo()
	shotPreviewServiceV0_1ServiceInfoForClient       = NewServiceInfoForClient()
	shotPreviewServiceV0_1ServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return shotPreviewServiceV0_1ServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return shotPreviewServiceV0_1ServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return shotPreviewServiceV0_1ServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ShotPreviewServiceV0_1"
	handlerType := (*v0_1.ShotPreviewServiceV0_1)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "v0_1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.0",
		Extra:           extra,
	}
	return svcInfo
}

func createShotPreviewTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*v0_1.ShotPreviewServiceV0_1CreateShotPreviewTaskArgs)
	realResult := result.(*v0_1.ShotPreviewServiceV0_1CreateShotPreviewTaskResult)
	success, err := handler.(v0_1.ShotPreviewServiceV0_1).CreateShotPreviewTask(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newShotPreviewServiceV0_1CreateShotPreviewTaskArgs() interface{} {
	return v0_1.NewShotPreviewServiceV0_1CreateShotPreviewTaskArgs()
}

func newShotPreviewServiceV0_1CreateShotPreviewTaskResult() interface{} {
	return v0_1.NewShotPreviewServiceV0_1CreateShotPreviewTaskResult()
}

func getShotPreviewTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*v0_1.ShotPreviewServiceV0_1GetShotPreviewTaskArgs)
	realResult := result.(*v0_1.ShotPreviewServiceV0_1GetShotPreviewTaskResult)
	success, err := handler.(v0_1.ShotPreviewServiceV0_1).GetShotPreviewTask(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newShotPreviewServiceV0_1GetShotPreviewTaskArgs() interface{} {
	return v0_1.NewShotPreviewServiceV0_1GetShotPreviewTaskArgs()
}

func newShotPreviewServiceV0_1GetShotPreviewTaskResult() interface{} {
	return v0_1.NewShotPreviewServiceV0_1GetShotPreviewTaskResult()
}

func cancelShotPreviewTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*v0_1.ShotPreviewServiceV0_1CancelShotPreviewTaskArgs)
	realResult := result.(*v0_1.ShotPreviewServiceV0_1CancelShotPreviewTaskResult)
	success, err := handler.(v0_1.ShotPreviewServiceV0_1).CancelShotPreviewTask(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newShotPreviewServiceV0_1CancelShotPreviewTaskArgs() interface{} {
	return v0_1.NewShotPreviewServiceV0_1CancelShotPreviewTaskArgs()
}

func newShotPreviewServiceV0_1CancelShotPreviewTaskResult() interface{} {
	return v0_1.NewShotPreviewServiceV0_1CancelShotPreviewTaskResult()
}

func retryShotPreviewTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*v0_1.ShotPreviewServiceV0_1RetryShotPreviewTaskArgs)
	realResult := result.(*v0_1.ShotPreviewServiceV0_1RetryShotPreviewTaskResult)
	success, err := handler.(v0_1.ShotPreviewServiceV0_1).RetryShotPreviewTask(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newShotPreviewServiceV0_1RetryShotPreviewTaskArgs() interface{} {
	return v0_1.NewShotPreviewServiceV0_1RetryShotPreviewTaskArgs()
}

func newShotPreviewServiceV0_1RetryShotPreviewTaskResult() interface{} {
	return v0_1.NewShotPreviewServiceV0_1RetryShotPreviewTaskResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateShotPreviewTask(ctx context.Context, request *v0_1.CreateShotPreviewTaskRequest) (r *v0_1.CreateShotPreviewTaskResponse, err error) {
	var _args v0_1.ShotPreviewServiceV0_1CreateShotPreviewTaskArgs
	_args.Request = request
	var _result v0_1.ShotPreviewServiceV0_1CreateShotPreviewTaskResult
	if err = p.c.Call(ctx, "CreateShotPreviewTask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetShotPreviewTask(ctx context.Context, request *v0_1.GetShotPreviewTaskRequest) (r *v0_1.GetShotPreviewTaskResponse, err error) {
	var _args v0_1.ShotPreviewServiceV0_1GetShotPreviewTaskArgs
	_args.Request = request
	var _result v0_1.ShotPreviewServiceV0_1GetShotPreviewTaskResult
	if err = p.c.Call(ctx, "GetShotPreviewTask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelShotPreviewTask(ctx context.Context, request *v0_1.CancelShotPreviewTaskRequest) (r *v0_1.CancelShotPreviewTaskResponse, err error) {
	var _args v0_1.ShotPreviewServiceV0_1CancelShotPreviewTaskArgs
	_args.Request = request
	var _result v0_1.ShotPreviewServiceV0_1CancelShotPreviewTaskResult
	if err = p.c.Call(ctx, "CancelShotPreviewTask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RetryShotPreviewTask(ctx context.Context, request *v0_1.RetryShotPreviewTaskRequest) (r *v0_1.RetryShotPreviewTaskResponse, err error) {
	var _args v0_1.ShotPreviewServiceV0_1RetryShotPreviewTaskArgs
	_args.Request = request
	var _result v0_1.ShotPreviewServiceV0_1RetryShotPreviewTaskResult
	if err = p.c.Call(ctx, "RetryShotPreviewTask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
